### ISSUE TITLE
Playbook path makes use of multiple path separators

### ISSUE THREAD

**Issue by fubarhouse** [fubarhouse/ansible-role-tester#42]

**Comment by issmirnov** [comment]
If you are looking for a quick and dirty hack, you could use [filepath.Abs](https://golang.org/pkg/path/filepath/#Abs).

Demo: https://play.golang.org/p/NFcFl7bQN4P

**Comment by fubarhouse** [comment]
@issmirnov,

That sure beats handling it manually as planned, thanks!

I had no idea that function existed.

**Comment by fubarhouse** [comment]
Test case on the provided example:

```sh
$ ansible-role-tester full --report
$ ansible-role-tester full --report --remote
```

Report 1:
```yaml
meta:
  timestamp: 2018-10-05T22:31:49.842276+10:00
  repository: https://github.com/issmirnov/ansible-role-compile-zsh.git
  commithash: d8ca090d961c258b84a691eafc48d157a9d55f21
  localchanges: false
  reportfile: report.yml
ansible:
  config:
    hostpath: /Users/karl/Projects/Ansible/ansible-role-compile-zsh
    inventory: ""
    remotepath: /etc/ansible/roles/role_under_test
    extrarolespath: ""
    librarypath: ""
    requirementsfile: ""
    playbookfile: tests/playbook.yml
    remote: false
    verbose: false
    quiet: false
  distribution:
    cid: ""
    name: ubuntu1804
    privileged: true
    container: fubarhouse/docker-ansible:bionic
    user: fubarhouse
    distro: ubuntu1804
    family:
      name: Ubuntu
      initialise: /sbin/init
      volume: /sys/fs/cgroup:/sys/fs/cgroup:ro
  hosts: []
  syntax: true
  requirements: false
  run:
    result: true
    time: 3m14.222329713s
  idempotence:
    result: true
    time: 10.424056797s
docker:
  run: true
  kill: true
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - /Users/karl/Projects/Ansible/ansible-role-compile-zsh:/etc/ansible/roles/role_under_test
  - /Users/karl/Projects/Ansible/ansible-role-compile-zsh:/etc/ansible/roles/ansible-role-compile-zsh
```

Report 2:
```yaml
meta:
  timestamp: 2018-10-05T22:36:39.693634+10:00
  repository: https://github.com/issmirnov/ansible-role-compile-zsh.git
  commithash: d8ca090d961c258b84a691eafc48d157a9d55f21
  localchanges: false
  reportfile: report.yml
ansible:
  config:
    hostpath: /Users/karl/Projects/Ansible/ansible-role-compile-zsh
    inventory: ""
    remotepath: /Users/karl/Projects/Ansible/ansible-role-compile-zsh
    extrarolespath: ""
    librarypath: ""
    requirementsfile: ""
    playbookfile: tests/playbook.yml
    remote: true
    verbose: false
    quiet: false
  distribution:
    cid: ""
    name: ubuntu1804
    privileged: true
    container: fubarhouse/docker-ansible:bionic
    user: fubarhouse
    distro: ubuntu1804
    family:
      name: Ubuntu
      initialise: /sbin/init
      volume: /sys/fs/cgroup:/sys/fs/cgroup:ro
  hosts: []
  syntax: false
  requirements: false
  run:
    result: false
    time: 1.70582763s
  idempotence:
    result: false
    time: 1.648012567s
docker:
  run: true
  kill: true
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - /Users/karl/Projects/Ansible/ansible-role-compile-zsh:/Users/karl/Projects/Ansible/ansible-role-compile-zsh
```

This is basically superseded from what I can tell... So if there's no argument to keep this open it will be closed in the next few days. Feedback is welcome to support keeping it open if a report can be provided with the described problem.
