### ISSUE TITLE
Thank you! 

### ISSUE THREAD

**Issue by issmirnov** [fubarhouse/ansible-role-tester#68]
@fubarhouse 

Just wanted to say thank you so much for building this epic tool. I've finally been able to delete about 90% of my code in the CI repo, and simply set up a single pipeline.yml for my concourse flow.

![pipeline](https://user-images.githubusercontent.com/5771615/46242186-66079700-c37a-11e8-89a8-df0680826c47.png)

Previously I had some wicked hacks with bash templatizers that would generate docker-compose files, spin up an ubuntu SSH docker image and an ubuntu ansible image, then have them link networks and run the roles. Now, it's as simple as [this](https://github.com/issmirnov/dcind#sample-pipeline):

```
      - task: run ansible-role-tester
        privileged: true
        params:
          ROLE: ansible-role-compile-zsh
        config:
          <<: *ansible_role_tester
          inputs:
            - name: art_bin
            - name: ansible-role-compile-zsh
          outputs:
            - name: report

```

This is so much more maintainable, and it runs much faster too. Amazing job!
