### ISSUE TITLE
--source flag requires --destination when invoked from alternate directory

### ISSUE THREAD

**Issue by issmirnov** [fubarhouse/ansible-role-tester#79]
Hi @fubarhouse,

I'm working on creating some tests for the exit-code issue, and noticed that they are failing due to incorrect mounts. It looks like the `--source` flag has had a regression. 

Tracing that flag, I see that it's assigned to `util.AnsibleConfig.HostPath` and then used [here](https://sourcegraph.com/github.com/fubarhouse/ansible-role-tester@d2e55e3dc8be839a4e90353e710a2e54f98fa8ce/-/blob/util/docker.go#L98). This should be working as intended.

Here's the full output of steps:

```shell
mkdir -p ~/tmp
cd tmp
git clone https://github.com/issmirnov/ansible-role-art-tester.git

# This run works.
cd ansible-role-art-tester && ansible-role-tester full --playbook tests/playbook-simple.yml 
```

Here's the failing command:
```shell
cd ~/tmp # CD to one level above. Any directory would work
ansible-role-tester full --playbook tests/playbook-simple.yml --source ~/tmp/ansible-role-art-tester --report

INFO[0000] Running 1538776416                           
5a6916fb39953d85075dac5b0c6a9c3c8a7aed623caae257cc45d63c720ad029
INFO[0000] Checking role hosts...                       
ERRO[0000] exit status 1                                
ERRO[0000] exit status 1                                
WARN[0000] Requirements file is not configured (empty/null), skipping... 
INFO[0000] Checking role syntax...                      
ERROR! the role 'ansible-role-art-tester' was not found in /etc/ansible/roles/role_under_test/tests/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/etc/ansible/roles/role_under_test/tests

The error appears to have been in '/etc/ansible/roles/role_under_test/tests/playbook-simple.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - ansible-role-art-tester
      ^ here

ERRO[0001] exit status 1                                
ERRO[0001] Syntax check: FAIL                           
INFO[0001] Running the role...                          
ERROR! the role 'ansible-role-art-tester' was not found in /etc/ansible/roles/role_under_test/tests/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/etc/ansible/roles/role_under_test/tests

The error appears to have been in '/etc/ansible/roles/role_under_test/tests/playbook-simple.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - ansible-role-art-tester
      ^ here

ERRO[0001] exit status 1                                
ERRO[0001] exit status 1                                
INFO[0001] Testing role idempotence...                  
ERROR! the role 'ansible-role-art-tester' was not found in /etc/ansible/roles/role_under_test/tests/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/etc/ansible/roles/role_under_test/tests

The error appears to have been in '/etc/ansible/roles/role_under_test/tests/playbook-simple.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - ansible-role-art-tester
      ^ here

ERRO[0002] exit status 1                                
ERRO[0002] empty error                                  
INFO[0002] Idempotence was checked in 491.640898ms      
ERRO[0002] Idempotence test: FAIL                       
INFO[0002] Stopping 1538776416                          
INFO[0012] Removing 1538776416                          

----------------------------------------------------------
Ansible Role Tester Report
----------------------------------------------------------
Timestamp: 			2018-10-05 14:53:36.270812395 -0700 PDT m=+0.005618482
Repository URL: 		https://github.com/issmirnov/ansible-role-art-tester.git
Repository commit: 		c4f4504d38b52287c5bc6ac2227d4fc4cb39cbda
Local changes: 			false
----------------------------------------------------------
Syntax check: 			false
Requirements installed: 	false
Run result: 			false
Run time: 			484.801187ms
Idempotence result: 		false
Idempotence time: 		491.651357ms
----------------------------------------------------------
Docker run: 			true
Docker kill: 			true
----------------------------------------------------------
```

Full report.yaml:

```yaml
meta:
  timestamp: 2018-10-05T14:59:28.668553795-07:00
  repository: https://github.com/issmirnov/ansible-role-art-tester.git
  commithash: c4f4504d38b52287c5bc6ac2227d4fc4cb39cbda
  localchanges: false
  reportfile: report.yml
ansible:
  config:
    hostpath: /home/issmirnov/tmp/ansible-role-art-tester
    inventory: ""
    remotepath: /etc/ansible/roles/role_under_test
    extrarolespath: ""
    librarypath: ""
    requirementsfile: ""
    playbookfile: tests/playbook-simple.yml
    remote: false
    verbose: false
    quiet: false
  distribution:
    cid: ""
    name: ubuntu1804
    privileged: true
    container: fubarhouse/docker-ansible:bionic
    user: fubarhouse
    distro: ubuntu1804
    family:
      name: Ubuntu
      initialise: /sbin/init
      volume: /sys/fs/cgroup:/sys/fs/cgroup:ro
  hosts: []
  syntax: false
  requirements: false
  run:
    result: false
    time: 503.405735ms
  idempotence:
    result: false
    time: 509.435417ms
docker:
  run: true
  kill: true
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - /home/issmirnov/tmp/ansible-role-art-tester:/etc/ansible/roles/role_under_test
  - /home/issmirnov/tmp/ansible-role-art-tester:/etc/ansible/roles/tmp
```

At least according to the report, this role should have been mounted to `/etc/ansible/roles/role_under_test` in the container.

I've reproduced this on two different machines, tested against my fork' `exit-code` branch as well as the master branch of this repo.

What do you think? I'll try to run some more analysis and inspect the docker container at runtime.

**Comment by issmirnov** [comment]
Ah, interesting. The following invocation works:

```shell
ansible-role-tester full --playbook tests/playbook-simple.yml --source ~/tmp/ansible-role-art-tester --report --destination /etc/ansible/roles/ansible-role-art-tester
```

I'm starting to understand. Normally I run `ansible-role-tester` at the root of the role I'm testing, so the implicit mount handled by the `pwd` logic linked above would mount the role in the expected location.

@fubarhouse do you think it makes sense to add logic that will parse the `source` path and mount the role into `/etc/ansible/roles`? This would be the exact same flow as the mount to `/etc/ansible/roles/role_under_test`

**Comment by fubarhouse** [comment]
Shell:
```
 11:36 PM:~/go/src/github.com/fubarhouse/ansible-role-tester $ git clone https://github.com/issmirnov/ansible-role-art-tester.git
Cloning into 'ansible-role-art-tester'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 24 (delta 2), reused 24 (delta 2), pack-reused 0
Unpacking objects: 100% (24/24), done.
 12:03 AM:~/go/src/github.com/fubarhouse/ansible-role-tester $ cd ansible-role-art-tester
 12:03 AM:~/go/src/github.com/fubarhouse/ansible-role-tester/ansible-role-art-tester $ 
 12:03 AM:~/go/src/github.com/fubarhouse/ansible-role-tester/ansible-role-art-tester $ ansible-role-tester full --playbook tests/playbook-simple.yml --source ~/tmp/ansible-role-art-tester --report
FATA[0000] Path /Users/karl/tmp/ansible-role-art-tester is not recognized as an Ansible role. 
 12:21 AM:~/go/src/github.com/fubarhouse/ansible-role-tester/ansible-role-art-tester $ ansible-role-tester full --playbook tests/playbook-simple.yml --source ~/tmp/ansible-role-art-tester --report
FATA[0000] Path /Users/karl/tmp/ansible-role-art-tester is not recognized as an Ansible role. 
 12:27 AM:~/go/src/github.com/fubarhouse/ansible-role-tester/ansible-role-art-tester $ ansible-role-tester full --playbook tests/playbook-simple.yml --source ~/go/src/github.com/fubarhouse/ansible-role-tester/ansible-role-art-tester --report
INFO[0000] Running 1538836090                           
987f28eb0f9157b94340dbb7db3ed109ddc43a04ef2a1e2e17048b8b3f30e8f8
INFO[0000] Checking role hosts...                       
ERRO[0002] exit status 1                                
ERRO[0002] exit status 1                                
WARN[0002] Requirements file is not configured (empty/null), skipping... 
INFO[0002] Checking role syntax...                      

playbook: /etc/ansible/roles/role_under_test/tests/playbook-simple.yml
INFO[0004] Syntax check: PASS                           
INFO[0004] Running the role...                          

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [ansible-role-art-tester : debug] *****************************************
ok: [localhost] => {
    "msg": "Task from ansible-role-art-tester. Answer: 42"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

INFO[0007] Role ran in 3.572811181s                     
INFO[0007] Testing role idempotence...                  

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [ansible-role-art-tester : debug] *****************************************
ok: [localhost] => {
    "msg": "Task from ansible-role-art-tester. Answer: 42"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

INFO[0011] Idempotence was checked in 3.746904162s      
INFO[0011] Idempotence test: PASS                       
INFO[0011] Stopping 1538836090
                         
INFO[0022] Removing 1538836090
                         

----------------------------------------------------------
Ansible Role Tester Report
----------------------------------------------------------
Timestamp:                      2018-10-07 00:28:10.837917 +1000 AEST m=+0.034900915
Repository URL:                 https://github.com/issmirnov/ansible-role-art-tester.git
Repository commit:              c4f4504d38b52287c5bc6ac2227d4fc4cb39cbda
Local changes:                  false
----------------------------------------------------------
Syntax check:                   true
Requirements installed:         false
Run result:                     true
Run time:                       3.572950589s
Idempotence result:             true
Idempotence time:               3.747033322s
----------------------------------------------------------
Docker run:                     true
Docker kill:                    true
----------------------------------------------------------

INFO[0022] Report data has been written to report.yml
```

Report:
```
meta:
  timestamp: 2018-10-07T00:04:58.028705+10:00
  repository: https://github.com/issmirnov/ansible-role-art-tester.git
  commithash: c4f4504d38b52287c5bc6ac2227d4fc4cb39cbda
  localchanges: false
  reportfile: report.yml
ansible:
  config:
    hostpath: /Users/karl/go/src/github.com/fubarhouse/ansible-role-tester/ansible-role-art-tester
    inventory: ""
    remotepath: /etc/ansible/roles/role_under_test
    extrarolespath: ""
    librarypath: ""
    requirementsfile: ""
    playbookfile: tests/playbook-simple.yml
    remote: false
    verbose: false
    quiet: false
  distribution:
    cid: ""
    name: ubuntu1804
    privileged: true
    container: fubarhouse/docker-ansible:bionic
    user: fubarhouse
    distro: ubuntu1804
    family:
      name: Ubuntu
      initialise: /sbin/init
      volume: /sys/fs/cgroup:/sys/fs/cgroup:ro
  hosts: []
  syntax: true
  requirements: false
  run:
    result: true
    time: 3.774652961s
  idempotence:
    result: true
    time: 3.488091306s
docker:
  run: true
  kill: true
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - /Users/karl/go/src/github.com/fubarhouse/ansible-role-tester/ansible-role-art-tester:/etc/ansible/roles/role_under_test
  - /Users/karl/go/src/github.com/fubarhouse/ansible-role-tester/ansible-role-art-tester:/etc/ansible/roles/ansible-role-art-tester
```

In the provided example, the mount is in fact mounting to the specified location (`/etc/ansible/roles/ansible-role-art-tester`). This is also reflected in your tests.

Could you please provide some steps to reproduce the problem?

**Comment by fubarhouse** [comment]
So I think I understand what is being asked more precisely here.

The mounts typically:
* Mount the source directory to `/etc/ansible/roles/role_under_test`
* Mount the source directory to the destination directory

I have attempted to test against the following inside and outside the directory of an Ansible role being tested and have not been able to replicate the problem.

I need you to do the following:
* Identify if this issue is still a problem
* Produce another set of steps to reproduce the problem with clear identifiers of success and failure against the latest version (`master`)

**Comment by issmirnov** [comment]
Sure, here's a reproduction. Thanks for looking into this!

1. Install an ansible repo

```bash
mkdir -p ~/tmp
cd tmp
git clone https://github.com/issmirnov/ansible-role-art-tester.git
tree .
```

At the end of this step, we have a folder `~/tmp` and a single role inside of it, at `~/tmp/ansible-role-art-tester`

2. Verify that running `ansible-role-tester` with working directory `~/tmp/ansible-role-art-tester` succeeds:

```bash
cd ~/tmp/ansible-role-art-tester
ansible-role-tester full --playbook tests/playbook-simple.yml
```

This demonstrates that the playbook does not have any errors and that the run is successful. The contents of `report.yml` are:

```bash
meta:
  timestamp: 2018-10-10T19:49:52.40019386-07:00
  repository: https://github.com/issmirnov/ansible-role-art-tester.git
  commithash: c4f4504d38b52287c5bc6ac2227d4fc4cb39cbda
  localchanges: false
  reportfile: report.yml
ansible:
  config:
    hostpath: /home/issmirnov/tmp/ansible-role-art-tester
    inventory: ""
    remotepath: /etc/ansible/roles/role_under_test
    extrarolespath: ""
    librarypath: ""
    requirementsfile: ""
    playbookfile: tests/playbook-simple.yml
    remote: false
    verbose: false
    quiet: false
  distribution:
    cid: ""
    name: ubuntu1804
    privileged: true
    container: fubarhouse/docker-ansible:bionic
    user: fubarhouse
    distro: ubuntu1804
    family:
      name: Ubuntu
      initialise: /sbin/init
      volume: /sys/fs/cgroup:/sys/fs/cgroup:ro
  hosts: []
  syntax: true
  requirements: false
  run:
    result: true
    time: 1.542265834s
  idempotence:
    result: true
    time: 1.561360359s
docker:
  run: true
  kill: true
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - /home/issmirnov/tmp/ansible-role-art-tester:/etc/ansible/roles/role_under_test
  - /home/issmirnov/tmp/ansible-role-art-tester:/etc/ansible/roles/ansible-role-art-tester
```

3. When we invoke `ansible-role-tester` from a different directory, and provide the `--source` flag but **NOT** the `--destination` flag, the run will fail.

```bash
cd ~/tmp # NOTE that this is NOT in a valid role directory
ansible-role-tester full --playbook tests/playbook-simple.yml --source ~/tmp/ansible-role-art-tester --report
```

The output report of step 3 looks like this:

```bash
INFO[0000] Running 1539225725                           
23dd808a6786caffbc1ab55dad506c11dfce5475cba09904bff3820f1393d9a0
INFO[0000] Checking role hosts...                       
ERRO[0000] exit status 1                                
ERRO[0000] exit status 1                                
WARN[0000] Requirements file is not configured (empty/null), skipping... 
INFO[0000] Checking role syntax...                      
ERROR! the role 'ansible-role-art-tester' was not found in /etc/ansible/roles/role_under_test/tests/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/etc/ansible/roles/role_under_test/tests

The error appears to have been in '/etc/ansible/roles/role_under_test/tests/playbook-simple.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - ansible-role-art-tester
      ^ here

ERRO[0001] exit status 1                                
ERRO[0001] Syntax check: FAIL                           
INFO[0001] Running the role...                          
ERROR! the role 'ansible-role-art-tester' was not found in /etc/ansible/roles/role_under_test/tests/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/etc/ansible/roles/role_under_test/tests

The error appears to have been in '/etc/ansible/roles/role_under_test/tests/playbook-simple.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - ansible-role-art-tester
      ^ here

ERRO[0001] exit status 1                                
ERRO[0001] exit status 1                                
INFO[0001] Testing role idempotence...                  
ERROR! the role 'ansible-role-art-tester' was not found in /etc/ansible/roles/role_under_test/tests/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/etc/ansible/roles/role_under_test/tests

The error appears to have been in '/etc/ansible/roles/role_under_test/tests/playbook-simple.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - ansible-role-art-tester
      ^ here

ERRO[0002] exit status 1                                
ERRO[0002] empty error                                  
INFO[0002] Idempotence was checked in 500.90305ms       
ERRO[0002] Idempotence test: FAIL                       
INFO[0002] Stopping 1539225725                          
INFO[0012] Removing 1539225725                          

----------------------------------------------------------
Ansible Role Tester Report
----------------------------------------------------------
Timestamp: 			2018-10-10 19:42:05.690039037 -0700 PDT m=+0.006058187
Repository URL: 		https://github.com/issmirnov/ansible-role-art-tester.git
Repository commit: 		c4f4504d38b52287c5bc6ac2227d4fc4cb39cbda
Local changes: 			false
----------------------------------------------------------
Syntax check: 			false
Requirements installed: 	false
Run result: 			false
Run time: 			486.907292ms
Idempotence result: 		false
Idempotence time: 		500.912558ms
----------------------------------------------------------
Docker run: 			true
Docker kill: 			true
----------------------------------------------------------

INFO[0013] Report data has been written to report.yml 
```

and the contents of `report.yml` are:

```yaml
meta:
  timestamp: 2018-10-10T19:42:05.690039037-07:00
  repository: https://github.com/issmirnov/ansible-role-art-tester.git
  commithash: c4f4504d38b52287c5bc6ac2227d4fc4cb39cbda
  localchanges: false
  reportfile: report.yml
ansible:
  config:
    hostpath: /home/issmirnov/tmp/ansible-role-art-tester
    inventory: ""
    remotepath: /etc/ansible/roles/role_under_test
    extrarolespath: ""
    librarypath: ""
    requirementsfile: ""
    playbookfile: tests/playbook-simple.yml
    remote: false
    verbose: false
    quiet: false
  distribution:
    cid: ""
    name: ubuntu1804
    privileged: true
    container: fubarhouse/docker-ansible:bionic
    user: fubarhouse
    distro: ubuntu1804
    family:
      name: Ubuntu
      initialise: /sbin/init
      volume: /sys/fs/cgroup:/sys/fs/cgroup:ro
  hosts: []
  syntax: false
  requirements: false
  run:
    result: false
    time: 486.907292ms
  idempotence:
    result: false
    time: 500.912558ms
docker:
  run: true
  kill: true
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - /home/issmirnov/tmp/ansible-role-art-tester:/etc/ansible/roles/role_under_test
  - /home/issmirnov/tmp/ansible-role-art-tester:/etc/ansible/roles/tmp
```



---


The **key** distinction here is the difference in volume mount paths.

When invoked from the role directory, the mount paths are:

```yaml
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - /home/issmirnov/tmp/ansible-role-art-tester:/etc/ansible/roles/role_under_test
  - /home/issmirnov/tmp/ansible-role-art-tester:/etc/ansible/roles/ansible-role-art-tester
```

Contrast this to the run where the working directory is `~/tmp` (not the role root) and we specify `--source` but not `--destination`. 

```yaml
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - /home/issmirnov/tmp/ansible-role-art-tester:/etc/ansible/roles/role_under_test
  - /home/issmirnov/tmp/ansible-role-art-tester:/etc/ansible/roles/tmp
```

We see here that `/home/issmirnov/tmp/ansible-role-art-tester` is mounted to `/etc/ansible/roles/ansible-role-art-tester` in the first case, but to `/etc/ansible/roles/tmp` in the second. This naturally causes the role search for `ansible-role-art-tester` to fail.

I believe this is due to [this statement](https://sourcegraph.com/github.com/fubarhouse/ansible-role-tester/-/blob/util/docker.go#L107). When the binary is invoked from `~/tmp`, the statement at line 106 will set `dir` to `tmp`, and will then bind the host path (`/home/issmirnov/tmp/ansible-role-art-tester`) to `fmt.Sprintf("/etc/ansible/roles/%v", dir)` which evaluates to `/etc/ansible/roles/tmp`.

Thus, there is no mount to `/etc/ansible/roles/ansible-role-art-tester` and the playbook fails.

I'm not sure what the best way to handle this is, since I haven't played with the `--source` and `--destination` flags too much, and I saw that there were some changes added for remote hosts and other interesting use cases. 

What do you think? I hope that this breakdown helps you reproduce this bug.
